### ISSUE TITLE
Sass-brunch is taking too long to compile

### ISSUE THREAD

**Issue by anildigital** [brunch/sass-brunch#167] opened 2017-12-26 13:56 UTC
I see this warning and it takes so much time (like couple minutes)

```Sass-brunch is taking too long to compile```

Any solution to speed this up. I am using Ubuntu Linux on my server.

**Comment by danschultzer** [comment] 2018-01-23 21:12
You should install from the master branch: `github:brunch/sass-brunch`

But honestly, brunch feels very broken if not dead at this point. No maintenance on a lot of their repos. You're probably better off switching to something like webpack.

**Comment by anildigital** [comment] 2018-03-03 17:08
@danschultzer thanks.. I am using master branch. It is still slow.. I am not sure it's making use of libsass on server. Any alternative way to use sass brunch?

**Comment by danschultzer** [comment] 2018-04-03 15:48
@anildigital we've switched to webpack instead of dealing with brunch.

**Comment by clarknelson** [comment] 2019-01-17 16:59
Switching to another code base is not a solution to the problem. 

Brunch is designed to be easy to use, minimal or no configuration. Webpack is designed for maximum customizability, with lots of configuration and pitfalls.

I will do my best to report my findings on this issue.

**Comment by clarknelson** [comment] 2019-01-17 17:10
I ran `npm update` which set sass-brunch at 2.10.8
After updating I no longer had a hanging compile process, it correctly output the error message "File to import not found or unreadable"
Feel free to investigate either before jumping ship to something more complicated.

**Comment by danschultzer** [comment] 2019-01-17 17:16
@clarknelson we had limited time to spend on this, and at the time there had been more than six months of no maintenance, and issues were piling up. We cut our losses and switched to something that was being actively maintained and that would work with recent versions of nodejs. There was no thoughts to as which one was better designed.

**Comment by paulmillr** [comment] 2019-01-17 18:52
@clarknelson any reproducible apps would be appreciated.

**Comment by clarknelson** [comment] 2019-01-17 22:21
@paulmillr sass-brunch was at 2.10.4 and there was an import statement in my code that did not resolve correctly. this may be enough to reproduce the error. I believe exactly it was `@import '../bower_component/etc/'` 

I had pasted almost 3k lines of code from a project I was migrating. Though the timeout might be just because it was large, but it compiled right away after removing the import statement.

If you have any other questions let me know. I don't think it's accurate to say that this repo is not maintained. 6 days ago the readme was updated, 19 days ago the code was updated, and at least 3 issues were closed in the last 5 days. If you want to switch build tools, I think you should put thought into which one is better designed.

**Comment by paulmillr** [comment] 2019-01-18 09:02
We are a bit tight on support resources, but definitely not dropping any maintenance. Webpack is obviously shit. If there was any good alternative to Brunch, i’d switch to work with it right away!

**Comment by clarknelson** [comment] 2019-01-18 15:31
@anildigital are you still experiencing this issue? It was no longer an issue for me after updating from `2.10.4` to `2.10.8`. I got an actual error message instead of multiple "compiling..." messages. For this reason I don't think it makes sense to make a test repo for an old version.

**Closed** 2023-02-09 12:17 UTC
